services:
    webserver:
        image: 'nginx:alpine'
        working_dir: /var/www
        volumes:
            - '.:/var/www'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8876:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /var/www
        volumes:
            - '.:/var/www'
            - ./database:/var/www/database:rw
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/cli/conf.d/99-overrides.ini'
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            PHP_IDE_CONFIG: "serverName=docker-debug"

#    db:
#        image: mysql:8.0
#        restart: always
#        volumes:
#            -   ./tmp/db:/var/lib/mysql
#        environment:
#            MYSQL_DATABASE: blogDB
#            MYSQL_ROOT_PASSWORD: root
#        ports:
#            -   '8101:3306'
#        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
